### ISSUE TITLE
Thank you! Any chance of adding QIIME2 Developer version classifer?

### ISSUE THREAD

**Issue by SpiderH** [colinbrislawn/unite-train#6]
Hi Colin,

Thank you very much for your sharing! May I ask if you trained the classifier with the developer version of the database? Is there any chance you could upload it?

As QIIME2 says " We recommend training UNITE classifiers on the full reference sequences. Furthermore, we recommend the “developer” sequences (located within the QIIME-compatible release download) because the standard versions of the sequences have already been trimmed to the ITS region (excluding portions of flanking rRNA genes that may be present in amplicons generated with standard ITS primers).".

I tried to train it using my own laptop allocating Ubuntu 22.04 40GB RAM and 60GB swap. Seems like it provides enough RAM but the CPU doesn't respond (nearly 0%). I could follow the tutorial classifier training of 85%OTU well. Would you be able to give me some suggestions on this?

Thank you very much and wish you all the best!

**Comment by colinbrislawn** [comment]
Hello!

Yes, the _dev files are used as input. See
https://github.com/colinbrislawn/unite-train/blob/main/workflow/Snakefile#L99

No region extraction or trimming is used, because UNITE does this for us, as you found in their docs.

> Seems like it provides enough RAM but the CPU doesn't respond (nearly 0%). 

The training part of this pipeline takes a lot of RAM but uses only one CPU thread. So if you have 16 cores and are using 1, 1/16 = 6.25% usage. It also takes much more then 40 GB of memory when I run it, so possibly your process has overflowed into swap and CPU is limited by disk I/O.

> Would you be able to give me some suggestions on this?

Sure! If you have a deadline and some money, I can bid for a small consulting project. My rates good!
Otherwise, I'm happy to answer questions about what I have already built.

**Comment by SpiderH** [comment]
> Yes, the _dev files are used as input.
Glad to know that and thank you for your sharing again! 

> The training part of this pipeline takes a lot of RAM but uses only one CPU thread.
It makes sense so much.

> If you have a deadline and some money, I can bid for a small consulting project.
Glad to know that as well. Hope some consulting in the future!

All the best to you, Colin. Thank you very much!

**Comment by SpiderH** [comment]
> Yes, the _dev files are used as input.

Glad to know that and thank you for your sharing again!




> The training part of this pipeline takes a lot of RAM but uses only one CPU thread.

It makes sense so much.


> If you have a deadline and some money, I can bid for a small consulting project.

Glad to know that as well. Hope some consulting in the future!

Thank you very much, Colin!

**Comment by colinbrislawn** [comment]
Would you like to close this issue for now or keep this open while we work through this?

**Comment by SpiderH** [comment]
Hi Colin, thanks for your reminder. I am quite new to GitHub. I would like to close it for now as the main topic is asking whether the classifier used _dev files as input. Thank you and see you later!
