### ISSUE TITLE
unite_ver9_dynamic_25.07.2023-Q2-2023.9.qza is not a QIIME2 artifact

### ISSUE THREAD

**Issue by zhinew15** [colinbrislawn/unite-train#7]
Hi all,

I am using the unite_ver9_dynamic_25.07.2023-Q2-2023.9.qza classifier in qiime2 2022.08 version and the system said it's not a qiime2 artifact, any thought? Thanks.

**Comment by colinbrislawn** [comment]
Hello,

I'm not sure why this happened... Maybe this is because the older install (2022.08) has an issue with the new artifact (2023.9). Does it work with the matching version of Qiime2?

Or maybe the download failed to finish and the file is corrupted. Can you re-download the artifact and check if the file size matches.

**Comment by zhinew15** [comment]
Hey Colin,

The download process was not corrupted, it may be the capability issue of version 2022.8.
However, I worked it out using the classify-consensus-vsearch method, which can be found in qiime2's tutorial. Thanks for your response.

**Comment by colinbrislawn** [comment]
I'm glad you got it working!

Before we close the issue, would you like to share the command that worked to help others?

**Comment by zhinew15** [comment]
Here is the link for this command: https://docs.qiime2.org/2023.9/plugins/available/feature-classifier/classify-consensus-vsearch/

**Comment by colinbrislawn** [comment]
Oh, I meant the specific series of commands that worked for you, as these may be different than the tutorials.

Or, if you would like, we can simply close this issue!
